import { describe, expect, it } from 'vitest';
import { HYDRONIC_PRESSURE_DROP_SCHEMA, HYDRONIC_REFERENCE_DATA_VERSION, evaluateHydronicSystem, hydronicVersionMetadata, type HydronicProject } from '../../src/engine/index.js';
import { itemizedCsv } from '../../src/app/reporting.js';
import { EDITOR_DRAFT_SCHEMA, PROJECT_FILE_SCHEMA, canonical, csvCell, parseProjectFile, validateDraft, validateProject } from '../../src/app/persistence.js';

const project: HydronicProject={schema:HYDRONIC_PRESSURE_DROP_SCHEMA,id:'p',name:'Project',calculationDataVersion:HYDRONIC_REFERENCE_DATA_VERSION,provenance:[],systems:[{id:'s',name:'System',fluidReferenceId:'iapws-liquid-water-sr6-08-2011',meanTemperatureF:60,pumpDischargeNodeId:'a',pumpSuctionNodeId:'b',nodes:[{id:'a',name:'A'},{id:'b',name:'B'}],sections:[],circuits:[],margin:{percent:0,categories:[],acknowledged:true}}]};
const projectWithCircuit=(): HydronicProject => ({...structuredClone(project),systems:[{...structuredClone(project.systems[0]!),pumpSuctionNodeId:'d',nodes:[{id:'a',name:'A'},{id:'b',name:'B'},{id:'c',name:'C'},{id:'d',name:'D'}],sections:[{id:'supply',name:'Supply',role:'supply',fromNodeId:'a',toNodeId:'b',geometry:{kind:'catalog',catalogId:'steel-sch40-1-5'},actualLengthFt:1,elements:[]},{id:'terminal',name:'Terminal',role:'terminal',fromNodeId:'b',toNodeId:'c',geometry:{kind:'catalog',catalogId:'steel-sch40-1-5'},actualLengthFt:1,elements:[]},{id:'return',name:'Return',role:'return',fromNodeId:'c',toNodeId:'d',geometry:{kind:'catalog',catalogId:'steel-sch40-1-5'},actualLengthFt:1,elements:[]}],circuits:[{id:'c',name:'Circuit',state:'active',terminalDesignGpm:1,supplySectionIds:['supply'],terminalSectionId:'terminal',returnSectionIds:['return']}]}]});
const fileWithSnapshot=()=>{const snapshotProject=projectWithCircuit();return {schema:PROJECT_FILE_SCHEMA,project:snapshotProject,metadata:hydronicVersionMetadata,acceptedSnapshot:{schema:'hydronic-pressure-drop-accepted-result@1',acceptedAt:'2026-01-01T00:00:00.000Z',project:structuredClone(snapshotProject),metadata:hydronicVersionMetadata,system:{id:'s',rawGoverningHeadFt:1,governingHeadFt:1.1,governingPressureLossPsi:.5,rawGoverningCircuitIds:['c'],factoredGoverningCircuitIds:['c'],circuits:[{circuitId:'c',rawHeadFt:1,marginHeadFt:.1,factoredHeadFt:1.1,pressureLossPsi:.5}]}}};};

describe('HYD-005 persistence boundaries',()=>{
  it('accepts a bounded normalized project and canonicalizes key order',()=>{expect(validateProject(project)).toHaveProperty('value');expect(canonical({b:1,a:{z:2,x:3}})).toBe(canonical({a:{x:3,z:2},b:1}));});
  it('rejects coercible numbers, bad schema, duplicate IDs and unsafe references',()=>{const numeric=structuredClone(project) as any;numeric.systems[0].meanTemperatureF='60';expect(validateProject(numeric)).toHaveProperty('error');const duplicate=structuredClone(project) as any;duplicate.systems[0].nodes.push({id:'a',name:'again'});expect(validateProject(duplicate)).toHaveProperty('error');const empty=structuredClone(project) as any;empty.systems=[];expect(validateProject(empty)).toHaveProperty('error');const wrong={schema:'future@2',project,metadata:{}};expect(parseProjectFile(JSON.stringify(wrong))).toHaveProperty('error');});
  it('accepts only public-engine loss category variants at the import boundary',()=>{const withLoss=(type:string,category:string)=>{const next=projectWithCircuit() as any;next.systems[0].sections[0].elements=[{id:'loss',type,category,quantity:1,applicability:{status:'unconfirmed',statedEnvelope:''},...(type==='k'?{k:1,basis:'section-inside-diameter'}:type==='equivalent-length'?{equivalentLengthFt:1,basis:'section-inside-diameter'}:type==='preset-equivalent-length'?{presetId:'doe-hdbk-1012-3-92-standard-90-elbow',basis:'section-inside-diameter'}:type==='cv'?{cv:1}:type==='direct-psi'?{pressureLossPsi:1}:{headFtOfSelectedFluid:1})}];return next;};for(const [type,category] of [['k','fitting'],['equivalent-length','valve'],['preset-equivalent-length','fitting'],['cv','equipment'],['direct-psi','valve'],['direct-head','equipment']])expect(validateProject(withLoss(type!,category!))).toHaveProperty('value');for(const [type,category] of [['k','pipe'],['equivalent-length','pipe'],['preset-equivalent-length','valve'],['preset-equivalent-length','equipment'],['preset-equivalent-length','pipe'],['cv','fitting'],['cv','pipe'],['direct-psi','fitting'],['direct-psi','pipe'],['direct-head','fitting'],['direct-head','pipe']])expect(validateProject(withLoss(type!,category!))).toHaveProperty('error');});
  it('rejects malformed accepted snapshots while retaining a structurally valid historical result',()=>{const valid=fileWithSnapshot();expect(parseProjectFile(JSON.stringify(valid))).toHaveProperty('value');const malformed=(change:(file:any)=>void)=>{const file=fileWithSnapshot() as any;change(file);expect(parseProjectFile(JSON.stringify(file))).toHaveProperty('error');};malformed(x=>x.acceptedSnapshot.system.rawGoverningCircuitIds=[3]);malformed(x=>x.acceptedSnapshot.system.factoredGoverningCircuitIds=['c','c']);malformed(x=>x.acceptedSnapshot.system.rawGoverningHeadFt=-1);malformed(x=>x.acceptedSnapshot.system.circuits[0].marginHeadFt=-.1);malformed(x=>x.acceptedSnapshot.system.id='other-system');malformed(x=>x.acceptedSnapshot.system.circuits[0].circuitId='other-circuit');malformed(x=>x.acceptedSnapshot.system.circuits.push(structuredClone(x.acceptedSnapshot.system.circuits[0])));});
  it('validates raw draft envelopes rather than accepting unknown keys',()=>{expect(validateDraft({schema:EDITOR_DRAFT_SCHEMA,project,raw:{'system:temperature':'1e'},errors:{'system:temperature':'Enter a complete decimal or scientific number.'},selected:'x'})).toHaveProperty('value');expect(validateDraft({schema:EDITOR_DRAFT_SCHEMA,project,raw:{'__proto__:x':'bad'},errors:{}})).toHaveProperty('error');});
  it('escapes CSV text and neutralizes formula cells without corrupting numeric values',()=>{expect(csvCell('hello,"world"\nnext')).toBe('"hello,""world""\nnext"');expect(csvCell(' =SUM(A1:A2)')).toBe("' =SUM(A1:A2)");expect(csvCell(-12.5)).toBe('-12.5');expect(csvCell(undefined)).toBe('');});
  it('exports evaluator circuit raw totals in itemized CSV rows',()=>{const reportProject=projectWithCircuit(),system=reportProject.systems[0]!,result=evaluateHydronicSystem(system),csv=itemizedCsv(reportProject,system,result,'Not accepted'),rows=csv.trim().split('\r\n').map(line=>line.split(',')),header=rows[0]!,items=rows.slice(1);const columns=Object.fromEntries(header.map((name,index)=>[name,index]));const circuit=result.circuits.find(x=>x.circuitId==='c')!,raw=Number(items[0]![columns.circuit_raw_ft!]!),itemTotal=items.reduce((sum,row)=>sum+Number(row[columns.item_head_ft!]!),0);expect(raw).toBe(circuit.rawHeadFt);expect(itemTotal).toBeCloseTo(circuit.rawHeadFt!,12);});
  it('rejects an unsupported versioned project envelope',()=>{expect(parseProjectFile(JSON.stringify({schema:PROJECT_FILE_SCHEMA,project,metadata:{schema:HYDRONIC_PRESSURE_DROP_SCHEMA,engineVersion:'wrong',referenceDataVersion:HYDRONIC_REFERENCE_DATA_VERSION}}))).toHaveProperty('error');});
});
