import { spawn } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { chromium } from 'playwright';
const chrome = process.env.HYDRONICS_CHROME ?? 'C:/Program Files/Google/Chrome/Application/chrome.exe';
if (!existsSync(chrome)) throw new Error(`Chrome not found at ${chrome}`);
const sourceText = readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8'); if (sourceText.includes('�') || !sourceText.includes(String.fromCodePoint(0x2014))) throw new Error('main.tsx must be valid UTF-8 and retain em-dash unavailable cells.');
const port = Number(process.env.HYDRONICS_PORT ?? '5175'); const baseUrl = `http://127.0.0.1:${port}`;
const server = spawn(process.execPath, ['./node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', String(port), '--strictPort'], { stdio: 'pipe' });
let browser;
try {
  await new Promise((resolve, reject) => { const timer=setTimeout(()=>reject(Error('Vite startup timeout')),15000); server.stdout.on('data',(x)=>{if(String(x).includes(String(port))){clearTimeout(timer);resolve();}}); server.once('error',reject); server.once('exit',(code)=>reject(Error(`Vite exited ${code}`))); });
  browser = await chromium.launch({ executablePath: chrome, headless: true, args: ['--no-first-run','--no-default-browser-check'] });
  const page = await browser.newPage({ viewport:{width:1440,height:1000} }); const failures=[]; const external=[];
  page.on('pageerror',(e)=>failures.push(`pageerror: ${e.message}`)); page.on('console',(m)=>{if(m.type()==='error')failures.push(`console: ${m.text()}`);}); page.on('request',(r)=>{if(!r.url().startsWith(baseUrl))external.push(r.url());});
  const load=async()=>page.goto(baseUrl,{waitUntil:'networkidle'});
  const tab=async(name)=>page.getByRole('tab',{name,exact:true}).click();
  const confirmAll=async()=>{await tab('Sections');for(const button of await page.getByRole('button',{name:'Confirm current basis'}).all())if(!await button.isDisabled())await button.click();};
  const results=page.getByRole('heading',{name:'Results / Show the math'}).locator('..');
  const ready=async()=>{ await page.getByRole('checkbox',{name:/I explicitly acknowledge/}).check(); };
  const common=()=>page.locator('article.section').filter({has:page.getByRole('heading',{name:/^Common supply/})});
  await load();
  const systemTab=page.getByRole('tab',{name:'System',exact:true}); if(await systemTab.getAttribute('aria-selected')!=='true') throw Error('System tab is not the default active tab.'); await systemTab.focus(); await page.keyboard.press('End'); if(await page.getByRole('tab',{name:'Files & report',exact:true}).getAttribute('aria-selected')!=='true') throw Error('End key did not select the final tab.'); await page.keyboard.press('Home'); if(await systemTab.getAttribute('aria-selected')!=='true') throw Error('Home key did not select the first tab.'); await page.keyboard.press('ArrowRight'); if(await page.getByRole('tab',{name:'Sections',exact:true}).getAttribute('aria-selected')!=='true') throw Error('Arrow key did not select the adjacent tab.');
  await tab('Sections'); const defaultSections=page.locator('article.section'); if(await defaultSections.count()!==6) throw Error('Default project did not render six physical Section PD cards.'); const defaultSectionText=await defaultSections.allTextContents(); if(!defaultSectionText.every((text)=>text.includes('Section PD'))||!defaultSectionText.find((text)=>text.includes('Common supply'))?.includes('unavailable')||!defaultSectionText.find((text)=>text.includes('Terminal 1 equipment'))?.includes('unavailable')||!defaultSectionText.find((text)=>text.includes('Terminal 2 equipment'))?.includes('unavailable')||!defaultSectionText.find((text)=>text.includes('Common return'))?.includes('unavailable')) throw Error('Gated Section PD rows did not fail closed before applicability confirmation.'); if(!defaultSectionText.find((text)=>text.includes('Branch 1'))?.includes('0.3742 ft / 0.1621 psi')||!defaultSectionText.find((text)=>text.includes('Branch 2'))?.includes('1.915 ft / 0.8294 psi')) throw Error(`Default available Section PD values are absent: ${defaultSectionText.join(' | ')}`);
  await tab('System'); await page.getByRole('checkbox',{name:/I explicitly acknowledge/}).check();
  await confirmAll(); await tab('Results'); await page.getByText('Calculation-ready-to-review').first().waitFor();
  const totalRows=results.locator('.section-totals tbody tr'); if(await totalRows.count()!==6) throw Error(`Section totals did not render exactly six physical rows: ${await totalRows.count()}`); const totalsText=await totalRows.allTextContents(); if(!totalsText[0]?.includes('Common supply')||!totalsText[1]?.includes('Branch 1')||!totalsText[3]?.includes('Branch 2')||totalsText.join(' ').includes('Grand total')) throw Error(`Section totals project order/grand-total contract failed: ${totalsText.join(' | ')}`);
  const initial=await results.innerText(); await tab('Sections'); const sectionFlows=(await page.locator('article.section .section-header').allTextContents()).join(' '); if(!initial.includes('Root flow: 30')||!sectionFlows.includes('30 GPM derived')||!sectionFlows.includes('10 GPM derived')||!sectionFlows.includes('20 GPM derived')) throw Error(`Synthetic 30/10/20 derived flows are absent: ${sectionFlows}`);
  if(!initial.includes('pipe ')||!initial.includes('fitting ')||!initial.includes('raw ')) throw Error('Circuit category/reconciliation output absent.');
  await tab('Results'); const circuit10=results.locator('article').filter({hasText:'circuit-10'}).first(), circuit20=results.locator('article').filter({hasText:'circuit-20'}).first();
  const parseTotals=(text)=>{const match=text.match(/raw ([\d.]+); margin [\d.]+; factored ([\d.]+); psi/); if(!match) throw Error(`Missing parseable circuit raw/factored totals: ${text}`); return {raw:Number(match[1]),factored:Number(match[2])};};
  await circuit20.getByRole('radio',{name:'Inspect'}).check(); if(!(await circuit20.getByRole('heading').innerText()).includes('selected inspector')) throw Error('Results Inspect did not select circuit 2 details.'); await tab('Circuits'); if(!await page.getByRole('radio',{name:'Inspect'}).nth(1).isChecked()) throw Error('Results Inspect did not synchronize the Circuits-tab radio state.'); await tab('Results');
  const before10=parseTotals(await circuit10.innerText()), before20=parseTotals(await circuit20.innerText());
  await tab('Sections'); await page.getByLabel('Common supply length ft').fill('120'); await tab('Results'); const after10=parseTotals(await circuit10.innerText()), after20=parseTotals(await circuit20.innerText()); if(after10.raw===before10.raw||after10.factored===before10.factored||after20.raw===before20.raw||after20.factored===before20.factored) throw Error('Shared length did not update parsed raw/factored totals for both circuits.');
  const headlineAfterLength=await results.locator('p').nth(1).innerText(); const governorParagraph=results.locator('p').filter({hasText:'Raw governing:'}); const governorsAfterLength=await governorParagraph.innerText(); if(!/Raw governing: [\d.]+ ft \(circuit-\d+\).*Factored governing: [\d.]+ ft \(circuit-\d+\)/.test(governorsAfterLength)) throw Error(`Governor heads/IDs are not directly captured: ${governorsAfterLength}`);
  await tab('Circuits'); await page.getByRole('radio',{name:'Inspect'}).nth(1).check(); await tab('Results'); if(await results.locator('p').nth(1).innerText()!==headlineAfterLength || await governorParagraph.innerText()!==governorsAfterLength) throw Error('Non-governing selection changed system headline/governors.');
  await tab('Sections'); const commonSection=common();
  const commonLoss=commonSection.locator('.loss').first(); await commonLoss.getByRole('button',{name:'Confirm current basis'}).click();
  await tab('Circuits'); await page.getByLabel('Terminal 2 / 20 GPM terminal design GPM').fill('40'); await tab('Results'); await page.getByText('Incomplete:').first().waitFor(); await tab('Sections');
  if(!(await commonLoss.innerText()).includes('stale') || !(await commonSection.innerText()).includes('50 GPM derived') || !((await commonSection.locator('.section-pd').textContent())?.includes('unavailable'))) throw Error(`Shared 50 GPM edit did not stale/fail-close the common Section PD: ${await commonSection.innerText()}`); await tab('Results'); if(!(await results.innerText()).includes('50 GPM')) throw Error('Shared 50 GPM stale basis evidence absent.');
  await confirmAll(); await tab('Results'); await page.getByText('Calculation-ready-to-review').first().waitFor(); await tab('Sections');
  const lossType=commonLoss.getByRole('combobox',{name:/Loss type/});
  const expectedCategories={k:['fitting','valve','equipment'],'equivalent-length':['fitting','valve','equipment'],'preset-equivalent-length':['fitting'],cv:['valve','equipment'],'direct-psi':['valve','equipment'],'direct-head':['valve','equipment']};
  for(const [type, expected] of Object.entries(expectedCategories)){ await lossType.selectOption(type); const actual=await commonLoss.locator('label').filter({hasText:'Category'}).locator('option').allTextContents(); if(actual.join('|')!==expected.join('|')) throw Error(`Wrong categories for ${type}: ${actual}`); }
  await lossType.selectOption('k'); await commonLoss.getByLabel('K',{exact:true}).fill('junk'); await lossType.selectOption('cv'); if(await commonLoss.getByLabel('K',{exact:true}).count()) throw Error('Old K control remained after type change.');
  await commonLoss.getByLabel('Cv',{exact:true}).fill('0'); if(await page.getByRole('alert').count()) throw Error('Obsolete type draft was not purged after deliberate replacement value.');
  await tab('Circuits'); await page.getByLabel('Terminal 1 / 10 GPM terminal design GPM').fill('1e'); await page.getByRole('radio',{name:'Inspect'}).nth(1).check(); await page.getByRole('alert').waitFor(); await tab('Results'); if(!(await results.innerText()).includes('Current headline unavailable')) throw Error('Invalid text did not withhold governing headline.');

  // Isolated regression scenarios for the remaining finite closure assertions.
  await load(); await tab('Sections'); const deletionSection=page.locator('article.section').last(); await page.getByRole('button',{name:'Add section'}).click(); const added=page.locator('article.section').last(); await added.getByRole('button',{name:'Add non-pipe loss'}).click(); if(!await page.getByRole('alert').count()) throw Error('New child loss did not expose its required-value error.'); await added.getByRole('button',{name:'Delete section'}).click(); if(await page.getByRole('alert').count()) throw Error('Deleting invalid child-loss section did not clear its gate/visible error.');

  await load(); await tab('Sections'); const commonOptional=common(); const description=commonOptional.getByLabel('Description'); await description.fill('temporary'); await description.fill(''); const provenance=commonOptional.locator('.loss').first().getByLabel(/Provenance/); await provenance.fill('temporary'); await provenance.fill(''); if(await description.inputValue()!==''||await provenance.inputValue()!=='') throw Error('Cleared description/provenance remained rendered.');

  await load(); await tab('Sections'); const basisLoss=common().locator('.loss').first(); if(!(await basisLoss.innerText()).includes('K 1.2')) throw Error('Current K=1.2 basis primitive is absent.'); await tab('System'); await page.getByRole('checkbox',{name:/I explicitly acknowledge/}).check(); await tab('Sections'); await basisLoss.getByRole('button',{name:'Confirm current basis'}).click(); if(!(await basisLoss.innerText()).includes('Captured basis:')||!(await basisLoss.innerText()).includes('K 1.2')) throw Error('Captured K=1.2 basis primitive is absent.');

  await load(); await tab('Sections'); const numericalLoss=common().locator('.loss').first(); await numericalLoss.getByRole('combobox',{name:/Loss type/}).selectOption('direct-head'); await numericalLoss.getByLabel('Actual-fluid head ft',{exact:true}).fill('1e308'); await numericalLoss.getByLabel('Quantity',{exact:true}).fill('2'); const numericalButton=numericalLoss.getByRole('button',{name:'Confirm current basis'}); if(!await numericalButton.isDisabled()||!(await numericalLoss.innerText()).match(/Cannot confirm:.*(representable|available|numerical)/i)) throw Error('Nonrepresentable direct-head target remained confirmable without reason.');
  await numericalLoss.getByRole('combobox',{name:/Loss type/}).selectOption('k'); await numericalLoss.getByLabel('Quantity',{exact:true}).fill('0'); if(!await page.getByRole('alert').count()||!await numericalLoss.getByRole('button',{name:'Confirm current basis'}).isDisabled()) throw Error('Quantity zero bypassed blank required coefficient.');

  await load(); await tab('Sections'); const geometry=common(); const pipe=geometry.getByRole('combobox',{name:/Pipe geometry/}); await pipe.selectOption('custom'); await geometry.getByLabel('Custom actual ID in',{exact:true}).fill('2'); await geometry.getByLabel('Custom roughness ft',{exact:true}).fill('0.0002'); if(!(await geometry.innerText()).includes('actual ID 2 in')) throw Error('Custom geometry display is not truthful.'); await pipe.selectOption('steel-sch40-1-5'); await geometry.getByLabel('Catalog roughness override ft',{exact:true}).fill('0.0002'); if(!(await geometry.innerText()).includes('catalog override')) throw Error('Catalog override display is absent.'); await geometry.getByRole('button',{name:'Use catalog default roughness'}).click(); if(!(await geometry.innerText()).includes('catalog default assumption')) throw Error('Catalog default reset display is absent.'); await pipe.selectOption('custom'); if(await geometry.getByLabel('Custom actual ID in',{exact:true}).inputValue()!=='1.5') throw Error('Custom/catalog mode reset did not expose model geometry truthfully.');

  await load(); await tab('Sections'); const routeCommon=common(), routeBranch=page.locator('article.section').filter({has:page.getByRole('heading',{name:/^Branch 1/})}); await routeCommon.getByRole('combobox',{name:/^From node/}).selectOption('split'); await routeCommon.getByRole('combobox',{name:/^To node/}).selectOption('t1'); await routeBranch.getByRole('combobox',{name:/^From node/}).selectOption('discharge'); await routeBranch.getByRole('combobox',{name:/^To node/}).selectOption('split'); await tab('Circuits'); const circuitEditor=page.getByRole('heading',{name:'Circuits'}).locator('..').locator('article').first(); await circuitEditor.locator('ol').first().locator('li').nth(1).getByRole('button',{name:'Up'}).click(); const routeText=await circuitEditor.innerText(); await tab('Results'); if(!routeText.includes('Ordered path: branch-1 → common-supply') || (await results.innerText()).includes('circuit:circuit-10: Supply sections are not continuous')) throw Error('Valid noninventory-ordered route did not persist without continuity error.');

  await load(); await tab('Sections'); const branch=page.locator('article.section').filter({has:page.getByRole('heading',{name:/^Branch 1/})}); await branch.getByRole('combobox',{name:/Pipe geometry/}).selectOption('custom'); await branch.getByLabel('Custom actual ID in',{exact:true}).fill('8'); await tab('Results'); if(!(await results.innerText()).includes('Transition flow')||!(await results.innerText()).includes('Incomplete:')) throw Error('Transition fixture did not produce incomplete output.');

  await load(); await tab('Sections'); const topologyCommon=common(); await topologyCommon.getByRole('combobox',{name:/^From node/}).selectOption('split'); await tab('Results'); const topologyText=await results.innerText(); await tab('Sections'); const activeLabels=(await page.locator('article.section .section-header').allTextContents()).join(' '); if(!topologyText.includes('circuit:circuit-10')||!activeLabels.includes('active reference; flow unavailable')||activeLabels.includes('Common supply (supply; unassigned/draft)')) throw Error('Located topology error or active-reference flow-unavailable label is missing.');

  await load(); await tab('System'); await ready(); await confirmAll(); await tab('Results'); const inspectResult=await results.innerText(); const recon=inspectResult.match(/Selected-inspector cumulative ([\d.]+) ft; authoritative circuit raw ([\d.]+) ft/); if(!recon||Math.abs(Number(recon[1])-Number(recon[2]))>1e-4) throw Error(`Whole-circuit cumulative does not reconcile: ${recon?.[0]}`);

  await tab('Files & report'); await page.getByRole('button',{name:'Load workbook example input reference'}).click(); await page.getByText('Loaded workbook example input reference. This draft input transcription has no portable topology or copied legacy results and requires engineering review before calculation or acceptance.').waitFor(); await tab('Sections'); const workbookSections=page.locator('article.section'); if(await workbookSections.count()!==31) throw Error(`Workbook input reference did not render 31 physical sections: ${await workbookSections.count()}`); if(!(await workbookSections.first().innerText()).includes('Section 01 — CHWR')||!(await workbookSections.nth(1).innerText()).includes('13.25')) throw Error('Workbook input reference did not render expected section identity/custom geometry.'); await tab('Results'); const workbookResults=await results.innerText(); if(!workbookResults.includes('Root flow: unavailable GPM')||!workbookResults.includes('System headline: unavailable')||workbookResults.includes('Calculation-ready-to-review')) throw Error(`Workbook input reference made an unavailable or copied governing claim: ${workbookResults.slice(0,1000)}`);
  await tab('Workbook reference'); const workbookReference=await page.locator('#panel-workbook').innerText(); if((await page.locator('#panel-workbook tbody tr').count())!==31||!workbookReference.includes('Reference-only transcription.')||!workbookReference.includes('Partial path available: 07 → 08 → 09 → 10 → 11 → 12 → 13 → 14 → 15 → 16 → 17 → 18 → 19 → 20 → 21 → 22 → 23 → 24 → 25 → 26 → 27 → 28 → 29 → 30 → 31')) throw Error('Workbook reference view did not preserve the static 31-row transcription and partial-path caution.');
  await tab('Files & report'); await page.getByRole('button',{name:'Load provisional 100 GPM workbook path'}).click(); await page.getByText('Partial inferred reconstruction: only the selected 100 GPM path is loaded; engine-derived section flows do not reproduce workbook header flows; not accepted or legacy-equivalent.').waitFor(); await tab('Circuits'); if(await page.getByLabel('Circuit name').inputValue()!=='Provisional selected 100 GPM path') throw Error('Provisional workbook path circuit did not load.'); await tab('Results'); const provisionalResults=await results.innerText(); if(!provisionalResults.includes('Root flow: 100 GPM')||!provisionalResults.includes('System headline: unavailable')||provisionalResults.includes('Calculation-ready-to-review')) throw Error(`Provisional workbook path did not remain fail-closed: ${provisionalResults.slice(0,1000)}`);
  await page.screenshot({path:process.env.HYDRONICS_SCREENSHOT ?? 'C:/Users/Victor Colosi/AppData/Local/Temp/hydronics-ui-repair-browser.png',fullPage:true});
  if(failures.length||external.length) throw Error([...failures,...external.map((x)=>`external request: ${x}`)].join('\n'));
  console.log('Browser checks passed: flows/reconciliation, shared update, stale/requalification, type cleanup, zero/raw invalid gating.');
} finally { await browser?.close(); if(!server.killed) server.kill(); }
