import { describe, expect, it } from 'vitest';
import { actualFluidPsiToHeadFt, colebrookDarcyFrictionFactor, currentApplicabilityBasis, evaluateHydronicSystem, evaluateSectionLoss, frictionHeadFtPer100Ft, headFtToActualFluidPsi, hydraulicState, isApplicabilityCurrent, type HydronicSystem, type LossElement, type LossElementData, type Section } from '../src/engine/index.js';
const water='iapws-liquid-water-sr6-08-2011' as const, pg='dowfrost-pg-50vol-2001-09' as const;
const geom={actualInsideDiameterIn:1.049,roughnessFt:.00015};
function row(data:LossElementData, flow=10, fluid: typeof water | typeof pg=water, temp=77, geometry=geom):LossElement { const draft={id:'x',...data,applicability:{status:'unconfirmed' as const,statedEnvelope:'qualified'}} as LossElement; const basis=currentApplicabilityBasis(flow,geometry,fluid,temp,draft); return {...draft,applicability:{status:'confirmed',statedEnvelope:'qualified',confirmedAtBasis:basis}} as LossElement; }
function section(elements:readonly LossElement[]=[], length=100, id='p'):Section{return {id,name:id,role:'supply',fromNodeId:'a',toNodeId:'b',geometry:{kind:'custom',...geom},actualLengthFt:length,elements};}
function invalidElement(data: unknown): LossElement { return {id:'bad',...(data as object),applicability:{status:'unconfirmed',statedEnvelope:'x'}} as LossElement; }
function systemWithTerminal(element: LossElement, margin: HydronicSystem['margin']={percent:0,categories:[],acknowledged:true}): HydronicSystem { const supply={...section([],0,'supply'),fromNodeId:'d',toNodeId:'a'},terminal={...section([element],0,'t'),role:'terminal' as const,fromNodeId:'a',toNodeId:'b'},returned={...section([],0,'return'),role:'return' as const,fromNodeId:'b',toNodeId:'u'}; return {id:'s',name:'s',fluidReferenceId:water,meanTemperatureF:77,pumpDischargeNodeId:'d',pumpSuctionNodeId:'u',nodes:['d','a','b','u'].map(id=>({id,name:id})),sections:[supply,terminal,returned],circuits:[{id:'c',name:'c',state:'active',terminalDesignGpm:10,supplySectionIds:['supply'],terminalSectionId:'t',returnSectionIds:['return']}],margin}; }

describe('G01 independent numeric baselines and conventions',()=>{
 it('retains water/PG goldens, independent Poiseuille arithmetic, named 49F, and separate legacy conventions',()=>{const w=evaluateSectionLoss(section(),10,water,77),p=evaluateSectionLoss(section(),1,pg,30);expect(w.hydraulicState?.velocityFtS).toBeCloseTo(3.7122620505542807,10);expect(w.hydraulicState?.reynoldsNumber).toBeCloseTo(33774.58316656881,7);expect(w.hydraulicState?.darcyFrictionFactor).toBeCloseTo(.027080012091821405,12);expect(w.headFt).toBeCloseTo(6.634316015514317,10);expect(w.pressureLossPsi).toBeCloseTo(2.867665205558536,10);expect(p.headFt).toBeCloseTo(.9697711599352945,10);const q=6.30901964e-5,d=1.049*.0254,mu=p.hydraulicState!.dynamicViscosityPaS,rho=p.hydraulicState!.densityKgM3;expect(128*mu*100*.3048*q/(Math.PI*d**4*rho*9.80665)/.3048).toBeCloseTo(.9697711599352945,10);expect(evaluateSectionLoss({...section([],15),geometry:{kind:'custom',actualInsideDiameterIn:10.02,roughnessFt:.00015}},1800,water,49).headFt).toBeCloseTo(.23173916134258887,9);const legacy={rhoLbFt3:62.412954115716,muLbFtS:.00089912434435185,gFtS2:32.2,roughnessFt:.00015,insideDiameterIn:10.02,lengthFt:15,flowGpm:1800};const diameterFt=legacy.insideDiameterIn/12,flowFt3S=legacy.flowGpm*(231/1728)/60,velocity=flowFt3S/(Math.PI*diameterFt**2/4),reynolds=legacy.rhoLbFt3*velocity*diameterFt/legacy.muLbFtS,relativeRoughness=legacy.roughnessFt/diameterFt;let low=.0025,high=.2;const residual=(f:number)=>1/Math.sqrt(f)+2*Math.log10(relativeRoughness/3.7+2.51/(reynolds*Math.sqrt(f)));for(let i=0;i<100;i+=1){const middle=(low+high)/2;if(residual(low)*residual(middle)>0)low=middle;else high=middle;}const friction=(low+high)/2,legacyHead=friction*(legacy.lengthFt/diameterFt)*velocity**2/(2*legacy.gFtS2),cacheHead=.23174664595943364;expect(reynolds).toBeCloseTo(424490.6434058245,6);expect(friction).toBeCloseTo(.015489555351622424,7);expect(legacyHead).toBeCloseTo(.23174550020482132,12);expect((legacyHead-cacheHead)/cacheHead).toBeCloseTo(-.0000049439965,12);expect(legacyHead).not.toBe(cacheHead);});
});

describe('G02 actual regimes, Colebrook and reporting',()=>{
 it.each([[1.0489999999999982,.5921609720944421,1999.999,'laminar',true],[1.0489999999999982,.5921612681750761,2000,'transition',false],[1.0489999999999982,1.1843225363501522,4000,'transition',false],[1.0489999999999984,1.1843228324307868,4000.001,'turbulent',true]] as const)('reports actual Re %s/%s',(d,q,re,regime,complete)=>{const s=evaluateSectionLoss({...section(),geometry:{kind:'custom',actualInsideDiameterIn:d,roughnessFt:.00015}},q,water,77);expect(s.hydraulicState?.reynoldsNumber).toBeCloseTo(re,8);expect(s.hydraulicState?.regime).toBe(regime);expect(s.complete).toBe(complete);if(complete) expect(s.headFt).toEqual(expect.any(Number)); else {expect(s.headFt).toBeUndefined();expect(s.diagnostics.some(diagnostic=>diagnostic.code==='transition-flow')).toBe(true);}});
 it('blocks transition at the system recommendation as well as the section result',()=>{const diameter=1.0489999999999982,flow=.5921612681750761,geometry={actualInsideDiameterIn:diameter,roughnessFt:.00015},input=systemWithTerminal(row({type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:1},flow,water,77,geometry));const result=evaluateHydronicSystem({...input,circuits:[{...input.circuits[0]!,terminalDesignGpm:flow}],sections:input.sections.map(s=>({...s,geometry:{kind:'custom' as const,...geometry}}))});expect(result.designEligible).toBe(false);expect(result.governingHeadFt).toBeUndefined();expect(result.sections.t?.hydraulicState?.reynoldsNumber).toBeCloseTo(2000,8);expect(result.sections.t?.diagnostics.some(d=>d.code==='transition-flow')).toBe(true);});
 it('checks independent Colebrook residual, invalid/unbracketed solver inputs, zero flow, and friction rate independent of physical length',()=>{const c=colebrookDarcyFrictionFactor(100000,.001);const residual=1/Math.sqrt(c.frictionFactor)+2*Math.log10(.001/3.7+2.51/(100000*Math.sqrt(c.frictionFactor)));expect(Math.abs(residual)).toBeLessThan(1e-8);for(const input of [[4000,.001],[100000,-1],[Infinity,.001],[4001,1e308]] as const)expect(()=>colebrookDarcyFrictionFactor(input[0],input[1])).toThrow();expect(evaluateSectionLoss(section([],0),0,water,77).headFt).toBe(0);const noLength=evaluateSectionLoss(section([],0),10,water,77),hundred=evaluateSectionLoss(section([],100),10,water,77);expect(noLength.headFt).toBe(0);expect(noLength.frictionHeadFtPer100Ft).toBeCloseTo(hundred.frictionHeadFtPer100Ft!,11);expect(evaluateSectionLoss(section([],100),1e-200,water,77).complete).toBe(false);});
});

describe('G03 evaluated loss/category/quantity matrix',()=>{
 const cases:[LossElementData,readonly ('fitting'|'valve'|'equipment')[],number][]=[[{type:'k',category:'fitting',quantity:1,k:.75,basis:'section-inside-diameter'},['fitting','valve','equipment'],.48186353347145255/3],[{type:'equivalent-length',category:'fitting',quantity:1,equivalentLengthFt:12,basis:'section-inside-diameter'},['fitting','valve','equipment'],1.592235843723436/2],[{type:'preset-equivalent-length',category:'fitting',quantity:1,presetId:'doe-hdbk-1012-3-92-standard-90-elbow',basis:'section-inside-diameter'},['fitting'],.3479698750137259/2],[{type:'preset-equivalent-length',category:'fitting',quantity:1,presetId:'doe-hdbk-1012-3-92-standard-45-elbow',basis:'section-inside-diameter'},['fitting'],.09279196667032691],[{type:'cv',category:'valve',quantity:1,cv:40},['valve','equipment'],1.298772888551391/9],[{type:'direct-psi',category:'valve',quantity:1,pressureLossPsi:3},['valve','equipment'],6.940471296288036],[{type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:8},['valve','equipment'],8]];
 const evaluated=cases.flatMap(([d,cats,per])=>cats.flatMap(category=>[0,1,2].map(quantity=>({d:{...d,category,quantity} as LossElementData,category,quantity,per}))));
 it.each(evaluated)('evaluates $category quantity $quantity with one pipe item and accounting parity',(x)=>{const r=evaluateSectionLoss(section([row(x.d)]),10,water,77);expect(r.complete).toBe(true);expect(r.items.filter(item=>item.kind==='pipe')).toHaveLength(1);expect(r.items).toHaveLength(2);expect(r.items[1]?.headFt).toBeCloseTo(x.per*x.quantity,9);expect(r.categoryHeadFt[x.category]).toBeCloseTo(x.per*x.quantity,9);expect(r.categoryHeadFt.pipe).toBeCloseTo(6.634316015514317,9);expect(r.headFt).toBeCloseTo(6.634316015514317+x.per*x.quantity,9);});
 it('retains K zero, rejects missing K, and proves K=f EL/D plus both current-ID DOE presets',()=>{expect(evaluateSectionLoss(section([row({type:'k',category:'fitting',quantity:1,k:0,basis:'section-inside-diameter'})]),10,water,77).complete).toBe(true);expect(evaluateSectionLoss(section([invalidElement({type:'k',category:'fitting',quantity:1,basis:'section-inside-diameter'})]),10,water,77).complete).toBe(false);const k=evaluateSectionLoss(section([row({type:'k',category:'fitting',quantity:1,k:.027080012091821405*12/(1.049/12),basis:'section-inside-diameter'})]),10,water,77),el=evaluateSectionLoss(section([row({type:'equivalent-length',category:'fitting',quantity:1,equivalentLengthFt:12,basis:'section-inside-diameter'})]),10,water,77);expect(k.items[1]?.headFt).toBeCloseTo(el.items[1]?.headFt!,10);for(const [preset,ratio] of [['doe-hdbk-1012-3-92-standard-90-elbow',30],['doe-hdbk-1012-3-92-standard-45-elbow',16]] as const){const standard=evaluateSectionLoss(section([row({type:'preset-equivalent-length',category:'fitting',quantity:1,presetId:preset,basis:'section-inside-diameter'})]),10,water,77);expect(standard.items[1]?.equivalentLengthFt).toBeCloseTo(ratio*1.049/12,12);const changedGeom={actualInsideDiameterIn:2,roughnessFt:.00015},changed=evaluateSectionLoss({...section([row({type:'preset-equivalent-length',category:'fitting',quantity:1,presetId:preset,basis:'section-inside-diameter'},10,water,77,changedGeom)]),geometry:{kind:'custom',...changedGeom}},10,water,77);expect(changed.items[1]?.equivalentLengthFt).toBeCloseTo(ratio*2/12,12);}});
});

describe('G04 invalid discriminated loss rows',()=>{
 const invalidCategories=[{type:'k',category:'pipe',k:1,basis:'section-inside-diameter'},{type:'equivalent-length',category:'pipe',equivalentLengthFt:1,basis:'section-inside-diameter'},{type:'preset-equivalent-length',category:'valve',presetId:'doe-hdbk-1012-3-92-standard-90-elbow',basis:'section-inside-diameter'},{type:'cv',category:'fitting',cv:1},{type:'direct-psi',category:'fitting',pressureLossPsi:1},{type:'direct-head',category:'fitting',headFtOfSelectedFluid:1}];
 const invalidScalars=[{type:'k',category:'fitting',basis:'section-inside-diameter'},{type:'equivalent-length',category:'fitting',equivalentLengthFt:-1,basis:'wrong'},{type:'preset-equivalent-length',category:'fitting',presetId:'missing',basis:'wrong'},{type:'cv',category:'valve',cv:0},{type:'direct-psi',category:'valve',pressureLossPsi:Infinity},{type:'direct-head',category:'equipment',headFtOfSelectedFluid:-1}];
 const invalidQuantities=[-1,.5,Infinity,'1'];
 it.each(invalidCategories)('rejects forbidden category for $type',(data)=>{const r=evaluateSectionLoss(section([invalidElement({...data,quantity:1})]),10,water,77);expect(r.complete).toBe(false);expect(r.headFt).toBeUndefined();expect(r.diagnostics.some(d=>d.location?.includes('element:bad'))).toBe(true);});
 it.each(invalidScalars)('rejects missing/invalid scalar, preset, or basis for $type',(data)=>{const r=evaluateSectionLoss(section([invalidElement({...data,quantity:0})]),10,water,77);expect(r.complete).toBe(false);expect(r.items[1]?.headFt).toBeUndefined();expect(r.diagnostics.length).toBeGreaterThan(0);});
 it.each([{type:'k',category:'fitting',quantity:1,k:'1',basis:'section-inside-diameter'},{type:'equivalent-length',category:'fitting',quantity:1,equivalentLengthFt:Infinity,basis:'section-inside-diameter'},{type:'preset-equivalent-length',category:'fitting',quantity:1,presetId:3,basis:'section-inside-diameter'},{type:'cv',category:'valve',quantity:1,cv:'40'},{type:'direct-psi',category:'equipment',quantity:1,pressureLossPsi:'3'},{type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:NaN}])('rejects wrong-type/nonfinite coefficient data for $type',(data)=>{const r=evaluateSectionLoss(section([invalidElement(data)]),10,water,77);expect(r.complete).toBe(false);expect(r.items[1]?.headFt).toBeUndefined();expect(r.diagnostics.some(d=>d.code==='invalid-input')).toBe(true);});
 it('isolates invalid category, quantity, coefficient, and basis mutations from otherwise-confirmed six-type rows',()=>{const valid=[{type:'k',category:'fitting',quantity:1,k:1,basis:'section-inside-diameter'},{type:'equivalent-length',category:'fitting',quantity:1,equivalentLengthFt:1,basis:'section-inside-diameter'},{type:'preset-equivalent-length',category:'fitting',quantity:1,presetId:'doe-hdbk-1012-3-92-standard-90-elbow',basis:'section-inside-diameter'},{type:'cv',category:'valve',quantity:1,cv:1},{type:'direct-psi',category:'equipment',quantity:1,pressureLossPsi:1},{type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:1}] as const;for(const data of valid){for(const mutation of [{category:'pipe'},{quantity:null},{...(data.type==='k'?{k:null}:data.type==='equivalent-length'?{equivalentLengthFt:NaN}:data.type==='preset-equivalent-length'?{basis:'wrong'}:data.type==='cv'?{cv:null}:data.type==='direct-psi'?{pressureLossPsi:null}:{headFtOfSelectedFluid:null})}]){const r=evaluateSectionLoss(section([{...row(data as LossElementData),...mutation} as LossElement]),10,water,77);expect(r.complete).toBe(false);expect(r.items[1]?.headFt).toBeUndefined();expect(r.diagnostics.some(d=>d.code==='invalid-input'&&d.location?.includes('element:x'))).toBe(true);}}});
 it.each(['k','equivalent-length','preset-equivalent-length','cv','direct-psi','direct-head'] as const)('rejects every invalid quantity domain for %s',(type)=>{const base=type==='k'?{type,category:'fitting',k:1,basis:'section-inside-diameter'}:type==='equivalent-length'?{type,category:'fitting',equivalentLengthFt:1,basis:'section-inside-diameter'}:type==='preset-equivalent-length'?{type,category:'fitting',presetId:'doe-hdbk-1012-3-92-standard-90-elbow',basis:'section-inside-diameter'}:type==='cv'?{type,category:'valve',cv:1}:type==='direct-psi'?{type,category:'valve',pressureLossPsi:1}:{type,category:'valve',headFtOfSelectedFluid:1};for(const quantity of invalidQuantities)expect(evaluateSectionLoss(section([invalidElement({...base,quantity})]),10,water,77).complete).toBe(false);});
 it('rejects malformed rows and missing applicability containers without throwing section/system APIs',()=>{for(const data of [{type:'unknown',category:'valve',quantity:1},{type:'cv',category:'valve',quantity:1,cv:1},{type:'direct-head',category:'pipe',quantity:1,headFtOfSelectedFluid:1}]){const malformed={id:'bad',...data} as LossElement;expect(()=>evaluateSectionLoss(section([malformed]),10,water,77)).not.toThrow();expect(evaluateSectionLoss(section([malformed]),10,water,77).complete).toBe(false);}const result=evaluateHydronicSystem(systemWithTerminal(invalidElement({type:'cv',category:'fitting',quantity:1,cv:1})));expect(result.designEligible).toBe(false);expect(result.circuits[0]?.complete).toBe(false);});
});

describe('G05 service and pressure semantics',()=>{
 it('blocks both DOE presets at actual laminar/transition Re while confirmed manual K/EL remain evaluable',()=>{const diameter=1.0489999999999982,serviceGeometry={actualInsideDiameterIn:diameter,roughnessFt:.00015},services=[[.5921609720944421,1999.999,'laminar'],[.5921612681750761,2000,'transition']] as const;for(const [flow,re,regime] of services)for(const presetId of ['doe-hdbk-1012-3-92-standard-90-elbow','doe-hdbk-1012-3-92-standard-45-elbow'] as const){const r=evaluateSectionLoss({...section([row({type:'preset-equivalent-length',category:'fitting',quantity:1,presetId,basis:'section-inside-diameter'},flow,water,77,serviceGeometry)]),geometry:{kind:'custom',...serviceGeometry}},flow,water,77);expect(r.hydraulicState?.reynoldsNumber).toBeCloseTo(re,8);expect(r.hydraulicState?.regime).toBe(regime);expect(r.complete).toBe(false);expect(r.items[1]?.headFt).toBeUndefined();}for(const data of [{type:'k',category:'fitting',quantity:1,k:.2,basis:'section-inside-diameter'},{type:'equivalent-length',category:'fitting',quantity:1,equivalentLengthFt:2,basis:'section-inside-diameter'}] as const){const flow=.5921609720944421,r=evaluateSectionLoss({...section([row(data,flow,water,77,serviceGeometry)]),geometry:{kind:'custom',...serviceGeometry}},flow,water,77);expect(r.hydraulicState?.regime).toBe('laminar');expect(r.complete).toBe(true);expect(r.items[1]?.headFt).toBeGreaterThan(0);}});
 it('distinguishes Cv density cancellation, direct psi actual-fluid head, direct head, and unconfirmed rows',()=>{const cvW=evaluateSectionLoss(section([row({type:'cv',category:'valve',quantity:1,cv:40},30)]),30,water,77),cvP=evaluateSectionLoss(section([row({type:'cv',category:'valve',quantity:1,cv:40},30,pg,30)]),30,pg,30),directP=evaluateSectionLoss(section([row({type:'direct-psi',category:'equipment',quantity:1,pressureLossPsi:3},30,pg,30)]),30,pg,30);expect(cvW.items[1]?.headFt).toBeCloseTo(1.298772888551391,9);expect(cvP.items[1]?.headFt).toBeCloseTo(1.298772888551391,9);expect(cvW.items[1]?.pressureLossPsi).not.toBeCloseTo(cvP.items[1]?.pressureLossPsi!,4);expect(actualFluidPsiToHeadFt(3,997.0470133997646)).toBeCloseTo(6.940471296288036,9);expect(directP.items[1]?.headFt).toBeCloseTo(6.563354603463994,9);expect(evaluateSectionLoss(section([invalidElement({type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:8})]),10,water,77).complete).toBe(false);});
});

describe('G06 current-basis lifecycle and isolation',()=>{
 it('invalidates every basis axis and requires explicit current requalification',()=>{const e=row({type:'k',category:'fitting',quantity:1,k:.2,basis:'section-inside-diameter'}),b=currentApplicabilityBasis(10,geom,water,77,e);const changed=[{...b,sectionGpm:11},{...b,fluidReferenceId:pg},{...b,meanTemperatureF:78},{...b,actualInsideDiameterIn:2},{...b,roughnessFt:.1},{...b,declaredEnvelope:'other'},{...b,referenceDataVersion:'other'},{...b,element:{...b.element,quantity:2}},{...b,element:{type:'cv',category:'valve',quantity:1,cv:2} as LossElementData}];for(const value of changed)expect(isApplicabilityCurrent({status:'confirmed',statedEnvelope:'qualified',confirmedAtBasis:b},value as never)).toBe(false);expect(isApplicabilityCurrent({status:'confirmed',statedEnvelope:'qualified',confirmedAtBasis:{...b,referenceDataVersion:undefined as never}},b)).toBe(false);});
 it('captures active selected-type primitives, ignores stale type fields, cannot be mutated, and is key-order independent',()=>{const raw={id:'raw',type:'cv' as const,category:'valve' as const,quantity:1,cv:40,k:999,applicability:{status:'unconfirmed' as const,statedEnvelope:'manual'}} as LossElement;const captured=currentApplicabilityBasis(10,geom,water,77,raw);(raw as unknown as {cv:number}).cv=5;expect(captured.element).toEqual({type:'cv',category:'valve',quantity:1,cv:40});const reordered={declaredEnvelope:captured.declaredEnvelope,element:{cv:40,quantity:1,category:'valve' as const,type:'cv' as const},roughnessFt:captured.roughnessFt,actualInsideDiameterIn:captured.actualInsideDiameterIn,meanTemperatureF:captured.meanTemperatureF,fluidReferenceId:captured.fluidReferenceId,sectionGpm:captured.sectionGpm,referenceDataVersion:captured.referenceDataVersion};expect(isApplicabilityCurrent({status:'confirmed',statedEnvelope:'manual',confirmedAtBasis:captured},reordered)).toBe(true);expect(isApplicabilityCurrent({status:'confirmed',statedEnvelope:'manual',confirmedAtBasis:captured},currentApplicabilityBasis(10,geom,water,77,{...raw,applicability:{status:'unconfirmed',statedEnvelope:'manual'}}))).toBe(false);});
 it('keeps common Cv confirmation stale after indirect 30-to-50 GPM shared flow change until explicit requalification',()=>{const common=row({type:'cv',category:'valve',quantity:1,cv:40},30);const make=(demand:number,commonElement=common):HydronicSystem=>({id:'shared',name:'shared',fluidReferenceId:water,meanTemperatureF:77,pumpDischargeNodeId:'d',pumpSuctionNodeId:'u',nodes:['d','m','a','b','u'].map(id=>({id,name:id})),sections:[{...section([commonElement],0,'common'),fromNodeId:'d',toNodeId:'m'},{...section([],0,'ta'),role:'terminal',fromNodeId:'m',toNodeId:'a'},{...section([],0,'tb'),role:'terminal',fromNodeId:'m',toNodeId:'b'},{...section([],0,'ra'),role:'return',fromNodeId:'a',toNodeId:'u'},{...section([],0,'rb'),role:'return',fromNodeId:'b',toNodeId:'u'}],circuits:[{id:'a',name:'a',state:'active',terminalDesignGpm:10,supplySectionIds:['common'],terminalSectionId:'ta',returnSectionIds:['ra']},{id:'b',name:'b',state:'active',terminalDesignGpm:demand,supplySectionIds:['common'],terminalSectionId:'tb',returnSectionIds:['rb']}],margin:{percent:0,categories:[],acknowledged:true}});expect(evaluateHydronicSystem(make(20)).designEligible).toBe(true);const stale=evaluateHydronicSystem(make(40));expect(stale.designEligible).toBe(false);expect(stale.sectionFlowGpm.common).toBe(50);const requalified=evaluateHydronicSystem(make(40,row({type:'cv',category:'valve',quantity:1,cv:40},50)));expect(requalified.sectionFlowGpm.common).toBe(50);expect(requalified.designEligible).toBe(true);});
});

describe('G07 numerical validity and failure reporting',()=>{
 it('rejects positive conversion underflow in both directions while retaining real zero',()=>{expect(()=>headFtToActualFluidPsi(Number.MIN_VALUE,997.0470133997646)).toThrow(RangeError);expect(()=>actualFluidPsiToHeadFt(Number.MIN_VALUE,10000)).toThrow(RangeError);expect(headFtToActualFluidPsi(0,997.0470133997646)).toBe(0);expect(actualFluidPsiToHeadFt(0,10000)).toBe(0);});
 it('reports pipe/state/factor/head/psi/category/section failures instead of false zero or overflow',()=>{for(const result of [evaluateSectionLoss(section([],Number.MIN_VALUE),10,water,77),evaluateSectionLoss(section([],100),1e-200,water,77),evaluateSectionLoss(section([],Number.MAX_VALUE),10,water,77),evaluateSectionLoss({...section([],100),geometry:{kind:'custom',actualInsideDiameterIn:1e200,roughnessFt:.00015}},10,water,77)]){expect(result.complete).toBe(false);expect(result.headFt).toBeUndefined();expect(result.diagnostics.some(d=>d.code==='numerical-failure'||d.code==='invalid-input')).toBe(true);}expect(()=>frictionHeadFtPer100Ft({...hydraulicState(10,geom,water,77),regime:'typo' as never},geom)).toThrow();const overflow=evaluateSectionLoss(section([{...row({type:'direct-head',category:'valve',quantity:Number.MAX_VALUE,headFtOfSelectedFluid:8}),id:'overflow-valve'},{...row({type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:1e308}),id:'overflow-equipment'}],0),10,water,77);expect(overflow.complete).toBe(false);expect(overflow.categoryHeadFt.valve).toBeUndefined();expect(overflow.diagnostics.some(d=>d.code==='numerical-failure')).toBe(true);});
 it('withholds aggregate active flow when finite terminal demands overflow its sum',()=>{const makeSection=(id:string,role:Section['role'],fromNodeId:string,toNodeId:string)=>({...section([],0,id),role,fromNodeId,toNodeId});const input:HydronicSystem={id:'aggregate',name:'aggregate',fluidReferenceId:water,meanTemperatureF:77,pumpDischargeNodeId:'d',pumpSuctionNodeId:'u',nodes:['d','a','b','c','e','u'].map(id=>({id,name:id})),sections:[makeSection('sa','supply','d','a'),makeSection('ta','terminal','a','b'),makeSection('ra','return','b','u'),makeSection('sb','supply','d','c'),makeSection('tb','terminal','c','e'),makeSection('rb','return','e','u')],circuits:[{id:'a',name:'a',state:'active',terminalDesignGpm:1e308,supplySectionIds:['sa'],terminalSectionId:'ta',returnSectionIds:['ra']},{id:'b',name:'b',state:'active',terminalDesignGpm:1e308,supplySectionIds:['sb'],terminalSectionId:'tb',returnSectionIds:['rb']}],margin:{percent:0,categories:[],acknowledged:true}};const result=evaluateHydronicSystem(input);expect(result.activeTerminalFlowGpm).toBeUndefined();expect(result.designEligible).toBe(false);expect(result.diagnostics.some(d=>d.code==='invalid-input'&&d.location==='system')).toBe(true);});
 it('retains true known zeros but diagnoses unrepresentable positive aggregate margin',()=>{
  const zero=evaluateSectionLoss(section([row({type:'direct-head',category:'equipment',quantity:0,headFtOfSelectedFluid:8})],0),10,water,77);
  expect(zero.complete).toBe(true); expect(zero.headFt).toBe(0);
  const tiny=row({type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:1e-100});
  const result=evaluateHydronicSystem(systemWithTerminal(tiny,{percent:1e-300,categories:['equipment'],acknowledged:true}));
  expect(result.designEligible).toBe(false); expect(result.circuits[0]?.marginHeadFt).toBeUndefined();
  expect(result.diagnostics.some(d=>d.code==='numerical-failure'&&d.location==='circuit:c')).toBe(true);
 });
});
