import { describe, expect, it } from 'vitest';
import { HYDRONIC_REFERENCE_DATA_VERSION, currentApplicabilityBasis, evaluateHydronicSystem, resolvePipeGeometry, type HydronicSystem, type LossElement, type LossElementData, type Section } from '../src/engine/index.js';

const water='iapws-liquid-water-sr6-08-2011' as const;
const geometry={kind:'custom' as const,actualInsideDiameterIn:1.049,roughnessFt:.00015};
function loss(id:string,data:LossElementData,flow:number,diameter=1.049):LossElement { const draft={id,...data,applicability:{status:'unconfirmed' as const,statedEnvelope:'fixture'}} as LossElement; return {...draft,applicability:{status:'confirmed' as const,statedEnvelope:'fixture',confirmedAtBasis:currentApplicabilityBasis(flow,{actualInsideDiameterIn:diameter,roughnessFt:.00015},water,77,draft)}} as LossElement; }
function pipe(id:string,role:Section['role'],fromNodeId:string,toNodeId:string,length=0,diameter=1.049,elements:readonly LossElement[]=[]):Section { return {id,name:id,role,fromNodeId,toNodeId,geometry:{kind:'custom',actualInsideDiameterIn:diameter,roughnessFt:.00015},actualLengthFt:length,elements}; }

/** Independent parent-oracle reverse-return fixture, with direct equipment heads. */
function reverse(draftB=false):any {
 const specs={S01:['supply','PD','S1',20,2.067],S12:['supply','S1','S2',35,2.067],S23:['supply','S2','S3',45,1.38],TA:['terminal','S1','R1',0,1.049],TB:['terminal','S2','R2',0,1.049],TC:['terminal','S3','R3',0,1.38],R12:['return','R1','R2',20,1.049],R23:['return','R2','R3',35,1.38],R30:['return','R3','PS',45,2.067]} as const;
 const sections:any[]=Object.entries(specs).map(([id,[role,from,to,length,diameter]])=>pipe(id,role as Section['role'],from,to,length,diameter));
 const configs=[['A',7,['S01'],'TA',['R12','R23','R30'],2],['B',11,['S01','S12'],'TB',['R23','R30'],20],['C',19,['S01','S12','S23'],'TC',['R30'],1]] as const;
 for(const [id,flow,_s,terminal,_r,head] of configs){const t=sections.find((s:any)=>s.id===terminal)!;t.elements=[loss(`${id}-equipment`,{type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:head},flow,(t.geometry as any).actualInsideDiameterIn)];}
 return {id:'reverse',name:'reverse',fluidReferenceId:water,meanTemperatureF:77,pumpDischargeNodeId:'PD',pumpSuctionNodeId:'PS',nodes:['PD','S1','S2','S3','R1','R2','R3','PS'].map(id=>({id,name:id})),sections,circuits:configs.map(([id,flow,supply,terminal,returned])=>({id,name:id,state:(draftB&&id==='B'?'draft':'active') as 'active'|'draft',terminalDesignGpm:flow,supplySectionIds:supply,terminalSectionId:terminal,returnSectionIds:returned})),margin:{percent:10,categories:['pipe','fitting','valve','equipment'],acknowledged:true}};
}
function twoPath():any { const a=loss('a',{type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:1},10),b=loss('b',{type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:2},20); return {id:'two',name:'two',fluidReferenceId:water,meanTemperatureF:77,pumpDischargeNodeId:'d',pumpSuctionNodeId:'u',nodes:['d','split','ai','ao','bi','bo','merge','u'].map(id=>({id,name:id})),sections:[pipe('s0','supply','d','split'),pipe('sa','supply','split','ai'),pipe('ta','terminal','ai','ao',0,1.049,[a]),pipe('ra','return','ao','merge'),pipe('sb','supply','split','bi'),pipe('tb','terminal','bi','bo',0,1.049,[b]),pipe('rb','return','bo','merge'),pipe('r0','return','merge','u')],circuits:[{id:'A',name:'A',state:'active',terminalDesignGpm:10,supplySectionIds:['s0','sa'],terminalSectionId:'ta',returnSectionIds:['ra','r0']},{id:'B',name:'B',state:'active',terminalDesignGpm:20,supplySectionIds:['s0','sb'],terminalSectionId:'tb',returnSectionIds:['rb','r0']}],margin:{percent:0,categories:[],acknowledged:true}}; }
function expectBlocked(result:ReturnType<typeof evaluateHydronicSystem>):void { expect(result.designEligible).toBe(false);expect(result.governingHeadFt).toBeUndefined();expect(result.factoredGoverningCircuitIds).toEqual([]);expect(result.diagnostics.length).toBeGreaterThan(0); }

describe('G08 valid direct/reverse return shared-flow goldens',()=>{
 it('retains direct-return 30-GPM sharing, result reuse, and no parallel-head sum',()=>{const r=evaluateHydronicSystem(twoPath());expect(r.designEligible).toBe(true);expect(r.activeTerminalFlowGpm).toBe(30);expect(r.sectionFlowGpm.s0).toBe(30);expect(r.sectionFlowGpm.r0).toBe(30);expect(r.circuits[0]?.sections[0]).toBe(r.circuits[1]?.sections[0]);expect(r.factoredGoverningCircuitIds).toEqual(['B']);});
 it('matches independent all-active reverse-return flows, asymmetric returns, circuit heads, and governing equipment path',()=>{const r=evaluateHydronicSystem(reverse());expect(r.designEligible).toBe(true);expect(r.activeTerminalFlowGpm).toBe(37);expect(r.sectionFlowGpm).toMatchObject({S01:37,S12:30,S23:19,TA:7,TB:11,TC:19,R12:7,R23:18,R30:37});expect(r.sections.S01).toBe(r.circuits[0]?.sections[0]);expect(r.sections.R30).toBe(r.circuits[2]?.sections.at(-1));expect(r.circuits.find(c=>c.circuitId==='A')?.factoredHeadFt).toBeCloseTo(6.746502236552526,9);expect(r.circuits.find(c=>c.circuitId==='B')?.factoredHeadFt).toBeCloseTo(26.46719778342044,9);expect(r.circuits.find(c=>c.circuitId==='C')?.factoredHeadFt).toBeCloseTo(6.389522061618318,9);expect(r.factoredGoverningCircuitIds).toEqual(['B']);});
 it('excludes draft B from all-active flow and reverse-return governing selection',()=>{const r=evaluateHydronicSystem(reverse(true));expect(r.designEligible).toBe(true);expect(r.activeTerminalFlowGpm).toBe(26);expect(r.sectionFlowGpm).toMatchObject({S01:26,S12:19,S23:19,TA:7,TC:19,R12:7,R23:7,R30:26});expect(r.sectionFlowGpm.TB).toBeUndefined();expect(r.circuits.map((c:any)=>c.circuitId)).toEqual(['A','C']);expect(r.circuits.find(c=>c.circuitId==='C')?.factoredHeadFt).toBeCloseTo(5.116487833457519,9);expect(r.factoredGoverningCircuitIds).toEqual(['C']);});
});

describe('G09 invalid topology blocks final output',()=>{
 const changes:{readonly name:string;readonly mutate:(s:any)=>void;readonly expected?:readonly [string,string]}[]=[
  {name:'unknown endpoint',mutate:s=>{s.sections[0]!.toNodeId='missing';},expected:['Section endpoints must be known distinct node IDs.','section:s0']},
  {name:'unknown section',mutate:s=>{s.circuits[0]!.supplySectionIds=['s0','missing'];},expected:['Circuit references an unknown section.','circuit:A']},
  {name:'self edge',mutate:s=>{s.sections[1]!.toNodeId=s.sections[1]!.fromNodeId;},expected:['Section endpoints must be known distinct node IDs.','section:sa']},
  {name:'reversed/discontinuous path',mutate:s=>{s.sections[1]!.fromNodeId='wrong';}},
  {name:'repeated section',mutate:s=>{s.circuits[0]!.supplySectionIds=['s0','s0'];}},
  {name:'duplicate node',mutate:s=>{s.nodes=[...s.nodes,{...s.nodes[0]!}];}},
  {name:'duplicate section',mutate:s=>{s.sections=[...s.sections,{...s.sections[0]!}];}},
  {name:'duplicate circuit',mutate:s=>{s.circuits=[...s.circuits,{...s.circuits[0]!}];},expected:['Circuit IDs must be unique.','circuit:A']},
  {name:'terminal reuse',mutate:s=>{s.circuits[1]!.terminalSectionId='ta';}},
  {name:'supply merge',mutate:s=>{s.sections.find((x:any)=>x.id==='sb')!.toNodeId='ai';}},
  {name:'return split',mutate:s=>{s.sections.find((x:any)=>x.id==='ra')!.fromNodeId='bo';}},
  {name:'supply/return node mixing',mutate:s=>{s.sections.find((x:any)=>x.id==='ra')!.toNodeId='split';}},
  {name:'internal cycle',mutate:s=>{s.sections.find((x:any)=>x.id==='ra')!.toNodeId='ai';}},
  {name:'discharge-root cycle',mutate:s=>{s.sections.push(pipe('back','supply','split','d'),pipe('again','supply','d','ai'));s.circuits[0]!.supplySectionIds=['s0','back','again'];}},
  {name:'suction-root cycle',mutate:s=>{s.sections.push(pipe('back','return','ao','u'),pipe('again','return','u','merge'));s.circuits[0]!.returnSectionIds=['back','again','r0'];}},
  {name:'terminal pump bypass',mutate:s=>{s.sections=[pipe('t','terminal','d','u')];s.nodes=[{id:'d',name:'d'},{id:'u',name:'u'}];s.circuits=[{id:'A',name:'A',state:'active',terminalDesignGpm:10,supplySectionIds:[],terminalSectionId:'t',returnSectionIds:[]}];}}
 ];
 it.each(changes)('rejects $name with topology/endpoint diagnostics',({mutate,expected})=>{const s=twoPath();mutate(s);const r=evaluateHydronicSystem(s);expectBlocked(r);expect(r.diagnostics.some(d=>d.code==='topology-error'||d.code==='invalid-input')).toBe(true);if(expected)expect(r.diagnostics.some(d=>d.message===expected[0]&&d.location===expected[1])).toBe(true);});
 it('retains a valid reverse-return control instead of rejecting its asymmetric route',()=>expect(evaluateHydronicSystem(reverse()).designEligible).toBe(true));
});

describe('G10 active completeness, membership, draft inventory, and final gating',()=>{
 it('keeps all known valid active references out of unused inventory when another active path field is malformed',()=>{const s=twoPath();s.circuits[0]!.supplySectionIds=['s0',42 as never];const r=evaluateHydronicSystem(s);expectBlocked(r);expect(r.topology.unusedSectionIds).toEqual([]);expect(r.topology.validCircuitIds).toEqual([]);});
 it('makes unknown circuit state/null records active-demand-indeterminate rather than a definite partial total',()=>{const s=twoPath();s.circuits=[s.circuits[0]!,{...s.circuits[1]!,state:'unknown' as never},null as never];const r=evaluateHydronicSystem(s);expectBlocked(r);expect(r.activeTerminalFlowGpm).toBeUndefined();});
 it('keeps correct all-active shared flows but withholds every final output for bad geometry/unqualified active loss',()=>{const badGeometry=twoPath();badGeometry.sections.find((s:any)=>s.id==='tb')!.geometry={kind:'custom',actualInsideDiameterIn:-1,roughnessFt:.00015};const geometryResult=evaluateHydronicSystem(badGeometry);expect(geometryResult.activeTerminalFlowGpm).toBe(30);expect(geometryResult.sectionFlowGpm.s0).toBe(30);expect(geometryResult.sections.tb?.categoryHeadFt.pipe).toBeUndefined();expectBlocked(geometryResult);const stale=twoPath();stale.sections.find((s:any)=>s.id==='tb')!.elements=[{...stale.sections.find((s:any)=>s.id==='tb')!.elements[0]!,applicability:{status:'unconfirmed',statedEnvelope:'draft'}} as LossElement];const staleResult=evaluateHydronicSystem(stale);expect(staleResult.sectionFlowGpm.s0).toBe(30);expect(staleResult.sections.tb?.complete).toBe(false);expect(staleResult.sections.tb?.headFt).toBeUndefined();expect(staleResult.sections.tb?.diagnostics.some((d:any)=>d.code==='incomplete-applicability')).toBe(true);expectBlocked(staleResult);});
 it('excludes valid draft and unused inventory, and has no governing result with no active circuit',()=>{const s=twoPath();s.sections=[...s.sections,pipe('unused','supply','d','split')];s.circuits=s.circuits.map((c:any)=>({...c,state:'draft' as const}));const r=evaluateHydronicSystem(s);expect(r.designEligible).toBe(false);expect(r.activeTerminalFlowGpm).toBeUndefined();expect(r.governingHeadFt).toBeUndefined();expect(r.topology.unusedSectionIds).toContain('unused');});
});

describe('G11 margin, governing selection, and ties',()=>{
 function crossover(percent=25):any { const a=loss('a',{type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:20},10),b=loss('b',{type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:9},10);const rate=6.634316015514317/100;return {id:'cross',name:'cross',fluidReferenceId:water,meanTemperatureF:77,pumpDischargeNodeId:'d',pumpSuctionNodeId:'u',nodes:['d','ai','ao','bi','bo','u'].map(id=>({id,name:id})),sections:[pipe('sa','supply','d','ai',10/rate),pipe('ta','terminal','ai','ao',0,1.049,[a]),pipe('ra','return','ao','u'),pipe('sb','supply','d','bi',20/rate),pipe('tb','terminal','bi','bo',0,1.049,[b]),pipe('rb','return','bo','u')],circuits:[{id:'A',name:'A',state:'active',terminalDesignGpm:10,supplySectionIds:['sa'],terminalSectionId:'ta',returnSectionIds:['ra']},{id:'B',name:'B',state:'active',terminalDesignGpm:10,supplySectionIds:['sb'],terminalSectionId:'tb',returnSectionIds:['rb']}],margin:{percent,categories:['pipe'],acknowledged:true}}; }
 it('uses percent units and selected categories to move the independent 30/29 crossover',()=>{const r=evaluateHydronicSystem(crossover());expect(r.circuits.find(c=>c.circuitId==='A')?.rawHeadFt).toBeCloseTo(30,8);expect(r.circuits.find(c=>c.circuitId==='B')?.rawHeadFt).toBeCloseTo(29,8);expect(r.circuits.find(c=>c.circuitId==='A')?.factoredHeadFt).toBeCloseTo(32.5,8);expect(r.circuits.find(c=>c.circuitId==='B')?.factoredHeadFt).toBeCloseTo(34,8);expect(r.rawGoverningCircuitIds).toEqual(['A']);expect(r.factoredGoverningCircuitIds).toEqual(['B']);const fraction=evaluateHydronicSystem(crossover(.25));expect(fraction.circuits.find(c=>c.circuitId==='A')?.marginHeadFt).toBeCloseTo(.025,8);});
 it('requires exact acknowledged Boolean and valid unique category/percent domains',()=>{for(const margin of [{percent:0,categories:[],acknowledged:false},{percent:-1,categories:[],acknowledged:true},{percent:Infinity,categories:[],acknowledged:true},{percent:25,categories:['pipe','pipe'],acknowledged:true},{percent:25,categories:['unknown'],acknowledged:true},{percent:25,categories:[],acknowledged:'true'}] as const){const r=evaluateHydronicSystem({...crossover(),margin:margin as never});expect(r.designEligible).toBe(false);expect(r.governingHeadFt).toBeUndefined();expect(r.diagnostics.some(d=>d.location==='margin')).toBe(true);}});
 it('returns every tied governing ID sorted despite circuit input reorder',()=>{const s=crossover(0);s.sections.find((x:any)=>x.id==='tb')!.elements=[loss('b',{type:'direct-head',category:'equipment',quantity:1,headFtOfSelectedFluid:20},10)];s.sections.find((x:any)=>x.id==='sb')!.actualLengthFt=s.sections.find((x:any)=>x.id==='sa')!.actualLengthFt;const forward=evaluateHydronicSystem(s),reordered=evaluateHydronicSystem({...s,circuits:[...s.circuits].reverse()});expect(forward.factoredGoverningCircuitIds).toEqual(['A','B']);expect(reordered.factoredGoverningCircuitIds).toEqual(['A','B']);});
});

describe('G12 runtime containers and identity boundaries',()=>{
 it.each([null,{}, {nodes:null}, {nodes:[],sections:null,circuits:[]}, {nodes:[],sections:[],circuits:null}, {id:42,nodes:[],sections:[],circuits:[]}])('rejects malformed system containers without coercion: %j',(raw)=>{const r=evaluateHydronicSystem(raw as never);expect(r.designEligible).toBe(false);expect(r.diagnostics.some(d=>d.code==='invalid-input')).toBe(true);});
 it.each(['constructor','toString','__proto__'])('supports reserved circuit IDs through success, diagnostics, and JSON own-key records: %s',(id)=>{const s=reverse();s.circuits=s.circuits.map((c:any)=>c.id==='B'?{...c,id}:c);const valid=evaluateHydronicSystem(s);expect(valid.designEligible).toBe(true);expect(valid.factoredGoverningCircuitIds).toEqual([id]);expect(Object.prototype.hasOwnProperty.call(valid.sectionFlowGpm,'S01')).toBe(true);expect(()=>JSON.stringify(valid)).not.toThrow();const invalid=evaluateHydronicSystem({...s,margin:{...s.margin,acknowledged:'bad' as never}});expect(invalid.designEligible).toBe(false);expect(invalid.diagnostics.some(d=>d.location==='margin')).toBe(true);});
 it('rejects malformed path/entry/IDs, enum and raw-number boundaries; geometry defaults only when absent',()=>{const s=twoPath();for(const mutation of [(x:any)=>{x.id='' as never;},(x:any)=>{x.nodes=[null as never];},(x:any)=>{x.sections=[null as never];},(x:any)=>{x.circuits[0]!.supplySectionIds=null as never;},(x:any)=>{x.circuits[0]!.id=42 as never;},(x:any)=>{x.sections[0]!.role='wrong' as never;},(x:any)=>{x.sections[0]!.geometry={kind:'wrong'} as never;}]){const input=twoPath();mutation(input);expect(evaluateHydronicSystem(input).designEligible).toBe(false);}expect(resolvePipeGeometry({kind:'catalog',catalogId:'steel-sch40-1'}).roughnessFt).toBe(.00015);expect(resolvePipeGeometry({kind:'catalog',catalogId:'steel-sch40-1',roughnessOverrideFt:undefined} as never).roughnessFt).toBe(.00015);for(const roughnessFt of [null,NaN,Infinity,-1])expect(()=>resolvePipeGeometry({kind:'catalog',catalogId:'steel-sch40-1',roughnessOverrideFt:roughnessFt} as never)).toThrow();for(const roughnessFt of [NaN,Infinity,-1])expect(()=>resolvePipeGeometry({kind:'custom',actualInsideDiameterIn:1.049,roughnessFt} as never)).toThrow();});
});
