import type { HydronicProject, HydronicSystem } from '../engine/contract.js';
import type { SystemLossResult } from '../engine/evaluator.js';
import { csvCell } from './persistence.js';

/** Item rows reuse evaluator output; no physics is recalculated for reporting. */
export function itemizedCsv(project: HydronicProject, system: HydronicSystem, result: SystemLossResult, status: string): string {
  const header=['project_id','project_name','system_id','system_name','circuit_id','section_id','item_id','item_kind','category','flow_gpm','actual_id_in','roughness_ft','reynolds','regime','darcy_factor','friction_ft_per_100ft','quantity','coefficient_or_basis','item_head_ft','item_psi','section_head_ft','circuit_raw_ft','circuit_margin_ft','circuit_factored_ft','circuit_psi','raw_governor','factored_governor','applicability_or_provenance','diagnostics','engine_version','reference_data_version','acceptance_status'];
  const source = new Map(system.sections.map(s=>[s.id,s])); const circuitBySection=new Map<string,string[]>(); for(const c of result.circuits)for(const id of c.sectionIds)circuitBySection.set(id,[...(circuitBySection.get(id)??[]),c.circuitId]);
  const rows:string[][]=[header]; for(const circuit of result.circuits)for(const sectionResult of circuit.sections){const section=source.get(sectionResult.sectionId); for(const item of sectionResult.items){const loss=section?.elements.find(x=>x.id===item.id); const coefficient=loss ? loss.type==='k'?`K ${loss.k}`:loss.type==='equivalent-length'?`EL ${loss.equivalentLengthFt} ft`:loss.type==='preset-equivalent-length'?loss.presetId:loss.type==='cv'?`Cv ${loss.cv}`:loss.type==='direct-psi'?`psi ${loss.pressureLossPsi}`:`head ${loss.headFtOfSelectedFluid} ft`:'automatic pipe'; const applicability=loss?`${loss.applicability.status}; ${loss.provenance?.note??''}`:'pipe friction'; rows.push([project.id,project.name,system.id,system.name,circuit.circuitId,sectionResult.sectionId,item.id,item.kind,item.category,sectionResult.flowGpm,sectionResult.geometry?.actualInsideDiameterIn,sectionResult.geometry?.roughnessFt,sectionResult.hydraulicState?.reynoldsNumber,sectionResult.hydraulicState?.regime,sectionResult.hydraulicState?.darcyFrictionFactor,sectionResult.frictionHeadFtPer100Ft,item.quantity,coefficient,item.headFt,item.pressureLossPsi,sectionResult.headFt,circuit.rawHeadFt,circuit.marginHeadFt,circuit.factoredHeadFt,circuit.pressureLossPsi,result.rawGoverningCircuitIds.includes(circuit.circuitId)?'yes':'',result.factoredGoverningCircuitIds.includes(circuit.circuitId)?'yes':'',applicability,item.diagnostics.map(d=>d.message).join(' | '),'hydronic-pressure-drop-engine@1.0.0','hydronic-reference-data@1.0.0',status].map(csvCell)); }} return rows.map(row=>row.join(',')).join('\r\n')+'\r\n';
}
